version: '3.4'

services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: netkacommitment
            MYSQL_USER: nkscommitment
            MYSQL_PASSWORD: nks@2015
        volumes:
            - ./../DB-Script/netkacommitment.sql:/docker-entrypoint-initdb.d/netkacommitment.sql
        networks:
            - default
        restart: always
    netkacommitment.web:
        image: ${DOCKER_REGISTRY-}netkacommitmentweb
        build:
            context: .
            dockerfile: NetkaCommitment.Web/Dockerfile
        links:
            - db:db
        ports:
            - 8888:8888
            - 9999:9999
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - "8000:80"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        restart: always